name: actionlint
on:
  workflow_call:
    inputs:
      fail-on-error:
        description: Should reviewdog fail when errors are found
        required: false
        default: true
        type: boolean
jobs:
  actions:
    name: Review Dog - Lint GitHub Actions Workflows
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@8ade135a41bc03ea155e62e844d188df1ea18608 # v4
      - name: Review Dog - actionlint
        uses: reviewdog/action-actionlint@82693e9e3b239f213108d6e412506f8b54003586 # v1
        with:
          fail_on_error: ${{inputs.fail-on-error}}
