name: Skip Duplicate Actions
on:
  workflow_call:
    outputs:
      should-skip:
        description: Whether the rest of the workflow should be skipped or not
        value: ${{ jobs.skip.outputs.should_skip }}
jobs:
  skip:
    runs-on: ubuntu-latest
    outputs:
      should_skip: ${{steps.skip.outputs.should_skip}}
    steps:
      - name: Skip Duplicate Actions
        uses: fkirc/skip-duplicate-actions@12aca0a884f6137d619d6a8a09fcc3406ced5281 # v5
        id: skip
