name: actionlint
on:
  workflow_call:
    inputs:
      fail-on-error:
        description: Should reviewdog fail when errors are found
        required: false
        default: true
        type: boolean
jobs:
  actions:
    name: Review Dog - Lint GitHub Actions Workflows
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@44c2b7a8a4ea60a981eaca3cf939b5f4305c123b # v4
      - name: Review Dog - actionlint
        uses: reviewdog/action-actionlint@89a03f6ba8c0a9fd238e82c075ffb34b86e40291 # v1
        with:
          fail_on_error: ${{inputs.fail-on-error}}
