name: actionlint
on:
  workflow_call:
    inputs:
      fail-on-error:
        description: Should reviewdog fail when errors are found
        required: false
        default: true
        type: boolean
jobs:
  actions:
    name: Review Dog - Lint GitHub Actions Workflows
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # v4
      - name: Review Dog - actionlint
        uses: reviewdog/action-actionlint@4797143fa54b2306fe78646b48cfa10395506635 # v1
        with:
          fail_on_error: ${{inputs.fail-on-error}}
