name: actionlint
on:
  workflow_call:
    inputs:
      fail-on-error:
        description: Should reviewdog fail when errors are found
        required: false
        default: true
        type: boolean
jobs:
  actions:
    name: Review Dog - Lint GitHub Actions Workflows
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4
      - name: Review Dog - actionlint
        uses: reviewdog/action-actionlint@2927e858b45218240af952feb1d702cf6365f39a # v1
        with:
          fail_on_error: ${{inputs.fail-on-error}}
