name: actionlint
on:
  workflow_call:
    inputs:
      fail-on-error:
        description: Should reviewdog fail when errors are found
        required: false
        default: true
        type: boolean
jobs:
  actions:
    name: Review Dog - Lint GitHub Actions Workflows
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4
      - name: Review Dog - actionlint
        uses: reviewdog/action-actionlint@4f8f9963ca57a41e5fd5b538dd79dbfbd3e0b38a # v1
        with:
          fail_on_error: ${{inputs.fail-on-error}}
