name: actionlint
on:
  workflow_call:
    inputs:
      fail-on-error:
        description: Should reviewdog fail when errors are found
        required: false
        default: true
        type: boolean
jobs:
  actions:
    name: Review Dog - Lint GitHub Actions Workflows
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac # v4
      - name: Review Dog - actionlint
        uses: reviewdog/action-actionlint@67ec075cacebd361442f6e3ef7671f74c6548909 # v1
        with:
          fail_on_error: ${{inputs.fail-on-error}}
