name: actionlint
on:
  workflow_call:
    inputs:
      fail-on-error:
        description: Should reviewdog fail when errors are found
        required: false
        default: true
        type: boolean
jobs:
  actions:
    name: Review Dog - Lint GitHub Actions Workflows
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@0ad4b8fadaa221de15dcec353f45205ec38ea70b # v4
      - name: Review Dog - actionlint
        uses: reviewdog/action-actionlint@51bfb044ddaed55059d16f14daedbe05a9937dc1 # v1
        with:
          fail_on_error: ${{inputs.fail-on-error}}
