name: ESLint
on:
  workflow_call:
    inputs:
      fail-on-error:
        description: Should reviewdog fail when errors are found
        required: false
        default: true
        type: boolean
jobs:
  eslint:
    name: Review Dog - ESLint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@1d96c772d19495a3b5c517cd2bc0cb401ea0529f # v4
      - name: Setup Node
        uses: actions/setup-node@60edb5dd545a775178f52524783378180af0d1f8 # v4
        with:
          cache-dependency-path: '**/package-lock.json'
          cache: npm
      - name: Install Dependencies
        run: npm ci
      - name: Review Dog - eslint
        uses: reviewdog/action-eslint@423672b7acbb75ee34d3e37aff30949ddc8350e3 # v1
        with:
          fail_on_error: ${{inputs.fail-on-error}}
