name: ESLint
on:
  workflow_call:
    inputs:
      fail-on-error:
        description: Should reviewdog fail when errors are found
        required: false
        default: true
        type: boolean
jobs:
  eslint:
    name: Review Dog - ESLint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # v4
      - name: Setup Node
        uses: actions/setup-node@60edb5dd545a775178f52524783378180af0d1f8 # v4
        with:
          cache-dependency-path: '**/package-lock.json'
          cache: npm
      - name: Install Dependencies
        run: npm ci
      - name: Review Dog - eslint
        uses: reviewdog/action-eslint@790a3d311c34b6f73294740617f9c2e9be493ae3 # v1
        with:
          fail_on_error: ${{inputs.fail-on-error}}
