name: Spellcheck
on: [workflow_call]
jobs:
  spellcheck:
    name: Lint Spelling
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@83b7061638ee4956cf7545a6f7efe594e5ad0247 # v3
      - name: Check Spelling
        uses: crate-ci/typos@7f65ff4f241e58ae048a1323ac77b9908ae0eb27 # v1.14.6
