name: Spellcheck
on: [workflow_call]
jobs:
  spellcheck:
    name: Lint Spelling
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@8ade135a41bc03ea155e62e844d188df1ea18608 # v4
      - name: Check Spelling
        uses: crate-ci/typos@509ec32112e5e1f0cb7551e37edd1fc6e79885d9 # v1.16.12
