name: Spellcheck
on: [workflow_call]
jobs:
  spellcheck:
    name: Lint Spelling
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab # v3
      - name: Check Spelling
        uses: crate-ci/typos@f37d3f8e3ccda00b2c60bba446e118337cb2d0ee # v1.15.0
