name: Spellcheck
on: [workflow_call]
jobs:
  spellcheck:
    name: Lint Spelling
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3
      - name: Check Spelling
        uses: crate-ci/typos@2fffb1bb2b8d72fc4f2b1905e573786d7ebbfbee # v1.15.6
