name: Spellcheck
on: [workflow_call]
jobs:
  spellcheck:
    name: Lint Spelling
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c # v3
      - name: Check Spelling
        uses: crate-ci/typos@26c2ca1853d0f0172f16e522e189b558dd15bfe0 # v1.13.12
