name: Spellcheck
on: [workflow_call]
jobs:
  spellcheck:
    name: Lint Spelling
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@755da8c3cf115ac066823e79a1e1788f8940201b # v3
      - name: Check Spelling
        uses: crate-ci/typos@6efbdc33f4385365c41520d44be74034513c8fcf # v1.13.6
