name: Spellcheck
on: [workflow_call]
jobs:
  spellcheck:
    name: Lint Spelling
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3
      - name: Check Spelling
        uses: crate-ci/typos@ccdede0f8c1e877aa3248b9c837f3f9b0abbbdf9 # v1.15.10
