name: Spellcheck
on: [workflow_call]
jobs:
  spellcheck:
    name: Lint Spelling
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@8f4b7f84864484a7bf31766abe9204da3cbe65b3 # v3
      - name: Check Spelling
        uses: crate-ci/typos@6cf303d4219d9188f418652067ae87d65833bc95 # v1.14.3
