name: Spellcheck
on: [workflow_call]
jobs:
  spellcheck:
    name: Lint Spelling
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4
      - name: Check Spelling
        uses: crate-ci/typos@c15b28fff9a814f9c12bd24cb1cfc114037e9187 # v1.20.4
