name: Spellcheck
on: [workflow_call]
jobs:
  spellcheck:
    name: Lint Spelling
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@8ade135a41bc03ea155e62e844d188df1ea18608 # v4
      - name: Check Spelling
        uses: crate-ci/typos@4550e7d4371fcf55649adfcda9b77716658504b1 # v1.16.17
