name: Spellcheck
on: [workflow_call]
jobs:
  spellcheck:
    name: Lint Spelling
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3
      - name: Check Spelling
        uses: crate-ci/typos@853cb28df37f6bc504fc6c6d9f134a534db8b9c4 # v1.16.9
