name: Spellcheck
on: [workflow_call]
jobs:
  spellcheck:
    name: Lint Spelling
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@8f4b7f84864484a7bf31766abe9204da3cbe65b3 # v3
      - name: Check Spelling
        uses: crate-ci/typos@66d82e5e516fa55d13c6ddd7288bf3bb4599fa59 # v1.14.5
