name: Spellcheck
on: [workflow_call]
jobs:
  spellcheck:
    name: Lint Spelling
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3
      - name: Check Spelling
        uses: crate-ci/typos@65d2fb6b91a696bfff5d59e7cf960cd7e51fb83a # v1.16.10
