name: Spellcheck
on: [workflow_call]
jobs:
  spellcheck:
    name: Lint Spelling
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4
      - name: Check Spelling
        uses: crate-ci/typos@b63f421581dce830bda2f597a678cb7776b41877 # v1.18.2
