name: Spellcheck
on: [workflow_call]
jobs:
  spellcheck:
    name: Lint Spelling
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3
      - name: Check Spelling
        uses: crate-ci/typos@ca9612c0458999d45c2f455a97ea3df2de805e00 # v1.16.0
