name: Spellcheck
on: [workflow_call]
jobs:
  spellcheck:
    name: Lint Spelling
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c # v3
      - name: Check Spelling
        uses: crate-ci/typos@28e7f17a65bc7dffccd8b8632578f9f3c730bffb # v1.13.23
