name: Spellcheck
on: [workflow_call]
jobs:
  spellcheck:
    name: Lint Spelling
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac # v4
      - name: Check Spelling
        uses: crate-ci/typos@509ec32112e5e1f0cb7551e37edd1fc6e79885d9 # v1.16.12
