name: Spellcheck
on: [workflow_call]
jobs:
  spellcheck:
    name: Lint Spelling
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c # v3
      - name: Check Spelling
        uses: crate-ci/typos@c389c36b661a3afb8dceaa91f25c887f58fc5abe # v1.13.16
