name: Spellcheck
on: [workflow_call]
jobs:
  spellcheck:
    name: Lint Spelling
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3
      - name: Check Spelling
        uses: crate-ci/typos@0863e64406a6d8f990ba7a1dd8f5a4683dd61194 # v1.16.5
