name: Spellcheck
on: [workflow_call]
jobs:
  spellcheck:
    name: Lint Spelling
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab # v3
      - name: Check Spelling
        uses: crate-ci/typos@7f65ff4f241e58ae048a1323ac77b9908ae0eb27 # v1.14.6
