name: Spellcheck
on: [workflow_call]
jobs:
  spellcheck:
    name: Lint Spelling
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c # v3
      - name: Check Spelling
        uses: crate-ci/typos@a50bd03c2ad90bd8c585a18bcae45791353ea81c # v1.13.20
