name: Spellcheck
on: [workflow_call]
jobs:
  spellcheck:
    name: Lint Spelling
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac # v4
      - name: Check Spelling
        uses: crate-ci/typos@65d2fb6b91a696bfff5d59e7cf960cd7e51fb83a # v1.16.10
