name: Spellcheck
on: [workflow_call]
jobs:
  spellcheck:
    name: Lint Spelling
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@24cb9080177205b6e8c946b17badbe402adc938f # v3
      - name: Check Spelling
        uses: crate-ci/typos@03286f0f825752c12a8521a4d2225b2f182f70b4 # v1.13.26
